### ISSUE TITLE
LNK2005

### ISSUE THREAD

**Issue by Infinax** [whizzter/rpoco#1]
extract_macro_names should be inline

**Comment by whizzter** [comment]
Will make it static, don't see a point in having an inline flag on a routine that should be called once per type. (Sorry for the late reply, been swamped with another thing for a week almost now)

**Comment by whizzter** [comment]
Sorry for the slowness, i was in the middle of adding a lot of comments (and some small rewrites of the parsing) when this issue came up at the same time as other things took priorty for me. It's fixed now though and thanks for noticing it.
